CREATE TABLE `archive_contracts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`organizationId` int,
	`originalFileUrl` varchar(512),
	`originalFileKey` varchar(512),
	`extractionStatus` enum('pending','processing','completed','failed','needs_review') NOT NULL DEFAULT 'pending',
	`extractionConfidence` int,
	`humanVerified` int DEFAULT 0,
	`verifiedBy` int,
	`verifiedAt` timestamp,
	`contractDate` timestamp,
	`projectType` enum('villa','apartment_building','commercial','mixed_use','industrial','hospitality','healthcare','educational','infrastructure','renovation','interior_only','other'),
	`emirate` enum('dubai','abu_dhabi','sharjah','ajman','ras_al_khaimah','fujairah','umm_al_quwain'),
	`area` varchar(255),
	`totalAreaSqm` double,
	`numFloors` int,
	`numUnits` int,
	`contractValueAed` double,
	`costPerSqmAed` double,
	`durationMonths` int,
	`scopeTags` text,
	`contractorType` enum('main_contractor','specialist','consultant','design_build'),
	`clientAnonymized` int DEFAULT 1,
	`specialConditions` text,
	`yearBucket` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `archive_contracts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `archive_drawings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contractId` int,
	`organizationId` int,
	`originalFileUrl` varchar(512),
	`originalFileKey` varchar(512),
	`drawingType` enum('floor_plan','elevation','section','site_plan','roof_plan','detail','3d_view','landscape') NOT NULL,
	`floorNumber` int,
	`scale` varchar(32),
	`extractionStatus` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
	`extractionConfidence` int,
	`totalAreaSqm` double,
	`netAreaSqm` double,
	`efficiencyRatio` double,
	`roomBreakdown` json,
	`facadeOrientation` varchar(32),
	`windowWallRatio` double,
	`styleTags` text,
	`designFeatures` text,
	`projectType` varchar(64),
	`emirate` enum('dubai','abu_dhabi','sharjah','ajman','ras_al_khaimah','fujairah','umm_al_quwain'),
	`designYear` int,
	`humanVerified` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `archive_drawings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `audit_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`actorType` enum('user','admin','system','api') NOT NULL,
	`actorId` int,
	`action` varchar(128) NOT NULL,
	`targetTable` varchar(64),
	`targetId` int,
	`beforeState` json,
	`afterState` json,
	`ipAddress` varchar(64),
	`metadata` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `audit_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cost_benchmarks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectType` enum('villa','apartment_building','commercial','mixed_use','industrial','hospitality','healthcare','educational','infrastructure','renovation','interior_only','other') NOT NULL,
	`emirate` enum('dubai','abu_dhabi','sharjah','ajman','ras_al_khaimah','fujairah','umm_al_quwain') NOT NULL,
	`year` int NOT NULL,
	`costPerSqmMin` double,
	`costPerSqmAvg` double,
	`costPerSqmMax` double,
	`costPerSqmStdDev` double,
	`sampleSize` int NOT NULL,
	`confidenceLevel` int,
	`inflationFactor` double,
	`marketNotesAr` text,
	`source` enum('archive_contracts','market_data','combined') DEFAULT 'archive_contracts',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cost_benchmarks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `data_expiry_alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tableName` varchar(64) NOT NULL,
	`recordId` int,
	`descriptionAr` text NOT NULL,
	`expiresAt` timestamp NOT NULL,
	`refreshIntervalDays` int,
	`status` enum('active','acknowledged','resolved') NOT NULL DEFAULT 'active',
	`acknowledgedBy` int,
	`acknowledgedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `data_expiry_alerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `data_versions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tableName` varchar(64) NOT NULL,
	`recordId` int NOT NULL,
	`version` int NOT NULL,
	`snapshot` json NOT NULL,
	`changeType` enum('created','updated','corrected','deprecated','restored') NOT NULL,
	`changedBy` int,
	`changeReason` text,
	`correctionId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `data_versions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `expert_corrections` (
	`id` int AUTO_INCREMENT NOT NULL,
	`submittedBy` int NOT NULL,
	`platform` enum('fada','raqaba','harara','maskan','code','khayal','all') NOT NULL,
	`correctionType` enum('building_code','calculation_rule','design_standard','material_spec','climate_data','general_knowledge') NOT NULL,
	`targetRecordId` int,
	`targetTable` varchar(64),
	`currentValueAr` text NOT NULL,
	`proposedValueAr` text NOT NULL,
	`justificationAr` text NOT NULL,
	`evidenceUrls` text NOT NULL,
	`officialReference` varchar(512),
	`status` enum('pending_review','under_review','approved','rejected','needs_more_info','applied') NOT NULL DEFAULT 'pending_review',
	`reviewerVotes` json,
	`appliedBy` int,
	`appliedAt` timestamp,
	`creditsAwarded` int DEFAULT 0,
	`priority` enum('low','normal','high','critical') DEFAULT 'normal',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `expert_corrections_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `expert_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`titleAr` varchar(128),
	`titleEn` varchar(128),
	`specialization` enum('structural','mechanical','electrical','civil','architectural','fire_safety','energy','interior_design','quantity_surveying','other') NOT NULL,
	`licenseNumber` varchar(64),
	`licensingBody` varchar(128),
	`yearsExperience` int,
	`organization` varchar(255),
	`verificationDocUrls` text,
	`verificationStatus` enum('pending','verified','rejected') NOT NULL DEFAULT 'pending',
	`verifiedBy` int,
	`verifiedAt` timestamp,
	`reputationScore` int DEFAULT 0,
	`correctionsSubmitted` int DEFAULT 0,
	`correctionsAccepted` int DEFAULT 0,
	`creditsEarned` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `expert_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `expert_profiles_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `gig_professionals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`specialization` enum('structural','mechanical','electrical','civil','architectural','fire_safety','energy','interior_design','quantity_surveying','bim_modeling','cost_estimation','other') NOT NULL,
	`skills` text,
	`yearsExperience` int,
	`preferredTaskTypes` text,
	`hourlyRateAed` double,
	`taskRates` json,
	`portfolioUrls` text,
	`licenseNumber` varchar(64),
	`verificationStatus` enum('pending','verified','rejected') NOT NULL DEFAULT 'pending',
	`ratingAvg` double DEFAULT 0,
	`ratingCount` int DEFAULT 0,
	`tasksCompleted` int DEFAULT 0,
	`totalEarningsAed` double DEFAULT 0,
	`isAvailable` int NOT NULL DEFAULT 1,
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `gig_professionals_id` PRIMARY KEY(`id`),
	CONSTRAINT `gig_professionals_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `gig_tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`postedBy` int,
	`platform` enum('fada','raqaba','harara','maskan','code','khayal','all') NOT NULL,
	`taskType` enum('boq_preparation','energy_study','drawing_review','code_checking','cost_estimation','inspection_report','design_review','quantity_survey','knowledge_entry','translation','other') NOT NULL,
	`titleAr` varchar(255) NOT NULL,
	`titleEn` varchar(255),
	`descriptionAr` text NOT NULL,
	`requiredSpecialization` varchar(128),
	`minExperience` int DEFAULT 0,
	`budgetAed` double,
	`deadline` timestamp,
	`attachmentUrls` text,
	`assignedTo` int,
	`assignedAt` timestamp,
	`status` enum('open','assigned','in_progress','submitted','approved','rejected','cancelled') NOT NULL DEFAULT 'open',
	`deliverableUrls` text,
	`qualityScore` int,
	`reviewNote` text,
	`paymentAed` double,
	`paymentStatus` enum('pending','released','held','refunded') DEFAULT 'pending',
	`knowledgeBaseImpact` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `gig_tasks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `project_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`uploadedBy` int NOT NULL,
	`docType` enum('architectural_drawing','structural_drawing','mep_drawing','contract','permit','inspection_report','cost_estimate','energy_study','soil_report','survey','photo','other') NOT NULL,
	`nameAr` varchar(255) NOT NULL,
	`nameEn` varchar(255),
	`fileUrl` varchar(512) NOT NULL,
	`fileKey` varchar(512) NOT NULL,
	`fileSizeBytes` int,
	`mimeType` varchar(128),
	`extractedData` json,
	`processingStatus` enum('pending','processing','completed','failed') DEFAULT 'pending',
	`version` int DEFAULT 1,
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `project_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`nameAr` varchar(255) NOT NULL,
	`nameEn` varchar(255),
	`projectType` enum('villa','apartment_building','commercial','mixed_use','industrial','hospitality','healthcare','educational','infrastructure','renovation','interior_only','feasibility','other') NOT NULL,
	`emirate` enum('dubai','abu_dhabi','sharjah','ajman','ras_al_khaimah','fujairah','umm_al_quwain'),
	`area` varchar(255),
	`plotNumber` varchar(64),
	`coordinates` varchar(64),
	`totalAreaSqm` double,
	`numFloors` int,
	`numUnits` int,
	`budgetAed` double,
	`phase` enum('feasibility','concept_design','schematic_design','design_development','construction_documents','permitting','construction','handover','completed') DEFAULT 'feasibility',
	`status` enum('active','on_hold','completed','cancelled') NOT NULL DEFAULT 'active',
	`coverImageUrl` varchar(512),
	`tags` text,
	`linkedSessionIds` json,
	`keyDecisions` json,
	`openIssues` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `projects_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `space_planning_benchmarks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectType` enum('villa','apartment_building','commercial','mixed_use','hospitality','healthcare','educational','other') NOT NULL,
	`spaceType` varchar(128) NOT NULL,
	`emirate` enum('dubai','abu_dhabi','sharjah','ajman','ras_al_khaimah','fujairah','umm_al_quwain'),
	`areaMinSqm` double,
	`areaAvgSqm` double,
	`areaMaxSqm` double,
	`areaRatioMin` double,
	`areaRatioAvg` double,
	`areaRatioMax` double,
	`typicalDimensions` varchar(128),
	`culturalNotesAr` text,
	`sampleSize` int NOT NULL,
	`source` enum('archive_drawings','standards','combined') DEFAULT 'archive_drawings',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `space_planning_benchmarks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `supplier_catalog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`supplierId` int NOT NULL,
	`platform` enum('fada','raqaba','harara','maskan','code','khayal','all') NOT NULL,
	`nameAr` varchar(255) NOT NULL,
	`nameEn` varchar(255),
	`category` varchar(128) NOT NULL,
	`descriptionAr` text,
	`descriptionEn` text,
	`specs` json,
	`priceAed` double,
	`priceUnit` varchar(32),
	`minOrderQty` double,
	`leadTimeDays` int,
	`imageUrls` text,
	`certifications` text,
	`thermalConductivity` double,
	`uValue` double,
	`shgc` double,
	`approvalStatus` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`approvedBy` int,
	`approvedAt` timestamp,
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `supplier_catalog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `suppliers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`nameAr` varchar(255) NOT NULL,
	`nameEn` varchar(255),
	`type` enum('manufacturer','distributor','contractor','consultant','retailer') NOT NULL,
	`specialization` enum('concrete','steel','insulation','glass','hvac','electrical','plumbing','finishing','furniture','landscaping','general') NOT NULL,
	`operatingEmirates` text,
	`phone` varchar(32),
	`email` varchar(320),
	`website` varchar(512),
	`address` text,
	`tradeLicenseNo` varchar(64),
	`verificationStatus` enum('pending','verified','rejected','suspended') NOT NULL DEFAULT 'pending',
	`verifiedBy` int,
	`verifiedAt` timestamp,
	`ratingAvg` double DEFAULT 0,
	`ratingCount` int DEFAULT 0,
	`trustScore` int DEFAULT 50,
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `suppliers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `trust_scores` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tableName` varchar(64) NOT NULL,
	`recordId` int NOT NULL,
	`score` int NOT NULL,
	`level` enum('unverified','community','verified','official','certified') NOT NULL,
	`sourceType` enum('government_official','expert_verified','peer_reviewed','supplier_submitted','ai_generated','user_contributed','market_data') NOT NULL,
	`justification` text,
	`lastCalculatedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `trust_scores_id` PRIMARY KEY(`id`)
);
