CREATE TABLE `partner_projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`partnerId` int NOT NULL,
	`nameAr` varchar(255) NOT NULL,
	`nameEn` varchar(255),
	`projectType` enum('villa','apartment_building','commercial','mixed_use','industrial','hospitality','healthcare','educational','infrastructure','renovation','interior_only','masterplan','feasibility','other') NOT NULL,
	`partnerRole` enum('main_contractor','subcontractor','developer','consultant','designer','supplier','project_manager','owner') NOT NULL,
	`emirate` enum('dubai','abu_dhabi','sharjah','ajman','ras_al_khaimah','fujairah','umm_al_quwain'),
	`country` varchar(64) DEFAULT 'UAE',
	`area` varchar(128),
	`totalAreaSqm` double,
	`numFloors` int,
	`numUnits` int,
	`contractValueAed` double,
	`showContractValue` int DEFAULT 0,
	`startDate` date,
	`completionDate` date,
	`durationMonths` int,
	`status` enum('completed','ongoing','on_hold','cancelled') NOT NULL DEFAULT 'completed',
	`descriptionAr` text,
	`descriptionEn` text,
	`highlightsAr` text,
	`challengesAr` text,
	`imageUrls` json,
	`documentUrls` json,
	`coverImageUrl` varchar(512),
	`contributesToBenchmarks` int DEFAULT 1,
	`actualCostPerSqmAed` double,
	`specLevel` enum('economy','standard','premium','luxury'),
	`clientNameAr` varchar(255),
	`showClientName` int DEFAULT 0,
	`approvalStatus` enum('pending','approved','rejected','needs_revision') NOT NULL DEFAULT 'pending',
	`approvedBy` int,
	`approvedAt` timestamp,
	`rejectionReason` text,
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `partner_projects_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `partner_reviews` (
	`id` int AUTO_INCREMENT NOT NULL,
	`partnerId` int NOT NULL,
	`reviewerId` int NOT NULL,
	`projectId` int,
	`rating` int NOT NULL,
	`qualityRating` int,
	`timelinessRating` int,
	`communicationRating` int,
	`valueRating` int,
	`reviewAr` text,
	`reviewEn` text,
	`isVerified` int DEFAULT 0,
	`isPublic` int DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `partner_reviews_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `partner_services` (
	`id` int AUTO_INCREMENT NOT NULL,
	`partnerId` int NOT NULL,
	`nameAr` varchar(255) NOT NULL,
	`nameEn` varchar(255),
	`serviceType` enum('product','service','design','consultation','inspection','study','training') NOT NULL,
	`platform` enum('fada','raqaba','harara','maskan','code','khayal','all') NOT NULL,
	`descriptionAr` text,
	`descriptionEn` text,
	`specs` json,
	`priceAed` double,
	`priceUnit` varchar(32),
	`priceIsNegotiable` int DEFAULT 1,
	`minOrderQty` double,
	`leadTimeDays` int,
	`imageUrls` json,
	`certifications` text,
	`approvalStatus` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `partner_services_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `partners` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`nameAr` varchar(255) NOT NULL,
	`nameEn` varchar(255),
	`partnerType` enum('supplier','contractor','developer','consultant','subcontractor','manufacturer') NOT NULL,
	`primarySpecialization` varchar(128) NOT NULL,
	`additionalSpecializations` json,
	`phone` varchar(32),
	`email` varchar(320),
	`website` varchar(512),
	`address` text,
	`operatingEmirates` json,
	`operatingCountries` json,
	`tradeLicenseNo` varchar(64),
	`tradeLicenseExpiry` date,
	`engineeringGrade` varchar(32),
	`professionalMemberships` text,
	`certifications` text,
	`foundedYear` int,
	`numEmployees` enum('1-10','11-50','51-200','201-500','500+'),
	`annualRevenueRange` enum('under_1m','1m_5m','5m_20m','20m_100m','100m_plus'),
	`profileAr` text,
	`profileEn` text,
	`logoUrl` varchar(512),
	`portfolioUrl` varchar(512),
	`verificationStatus` enum('pending','under_review','verified','rejected','suspended') NOT NULL DEFAULT 'pending',
	`verifiedBy` int,
	`verifiedAt` timestamp,
	`rejectionReason` text,
	`ratingAvg` double DEFAULT 0,
	`ratingCount` int DEFAULT 0,
	`trustScore` int DEFAULT 50,
	`isPublicListed` int NOT NULL DEFAULT 0,
	`isActive` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `partners_id` PRIMARY KEY(`id`)
);
